### ISSUE TITLE
dotnetuser 80 port Permission denied

### ISSUE THREAD

**Issue by dyw770** [streetwriters/notesnook-sync-server#5]
dotnetuser user does not have permission to listen on port 80.
![image](https://github.com/user-attachments/assets/ea3c3dc4-284f-4293-bb20-c1f86fd45d0f)
temporary solution:

```yaml
 identity-server:
    image: streetwriters/identity:latest
    user: "root:root"
    ports:
      - 8264:80
    networks:
      - notesnook
    env_file: *env-files
```
